### ISSUE TITLE
min sdk API level 21(android 5.0)?

### ISSUE THREAD

**Issue by DI555** [otakuhqz/Omega#25]
could it be possible to set min sdk API level 21(android 5.0)?
i have a lots of devices with that minsdk21...

**Comment by otakuhqz** [comment]
It might be possible but I would take a lot of work to validate the features of the newer versions.

I will make a test in the next days and if there are few issues, I will try to compile apk.

I'm not certainly sure if that would work since a lot of features are available for API 26 and above (icon shape, gestures, app Predictions, Google feed, at glance widget, etc, etc).

**Comment by DI555** [comment]
great, wil wait for it very much!!!
(i'm not keen in it, but there're some features, you know, like using 'desugaring' or so...and using gradle plugin when compilling..., - all for compile compatible package for min_api 21 imho...)

**Comment by machiav3lli** [comment]
Desugaring removes the java version's dependency for the most part, but all the deprecated APIs or at-that-time-not-yet-existing APIs are a wholesome problem and the effort to deal with them could be enormous.

**Comment by otakuhqz** [comment]
As @machiav3lli says it would require a huge effort to make it work. I just tried with version 7.1.1  (which is the min required version) and there is a lot of issues crash that required time to fix it.
That being said, the support for APIs lower than 25 would not be possible.
