### ISSUE TITLE
Please provide an F-Droid package

### ISSUE THREAD

**Issue by l3u** [otakuhqz/Omega#9]
As this is the successor of Zim Launcher (which I have been using for quite some time now, but it's not developed anymore), it would be very nice if one could install Omega via the F-Droid store.

Thanks for your great work :-)

**Comment by otakuhqz** [comment]
That would be a little difficult at this moment due to F-Droid compile their own APKs and they don't allow to have compiled jar libraries unless they are uploaded into a maven/Gradle repository.
The App will not compile at this moment without that libraries. 
I would deal with that later as I want to have as many features as possible.

**Comment by l3u** [comment]
Okay, thanks for the info! As long as you plan to provide Omega on F-Droid when it's possible to do so, I'm completely fine with it ;-)

**Comment by otakuhqz** [comment]
the app is now in F-Droid. You should add the below repository to your f-droid app (Credit @rafaelvenancio98)
[Omega Repository](https://raw.githubusercontent.com/rafaelvenancio98/fdroid/master/fdroid/repo)

**Comment by l3u** [comment]
Nice! Great work!

**Comment by linsui** [comment]
Do you have a plan to distribute it in F-Droid's official repo?

**Comment by nonaybay** [comment]
[](https://raw.githubusercontent.com/nonaybay/OmegaRelease/master/fdroid/repo?fingerprint=3CD4431A5B16DFF09A68D292A8C22977B483517DB39F237D16DE28D5C5421FCC)Release
